"""empty message

Revision ID: 5aab647f5151
Revises: 5f07701d2bb2
Create Date: 2021-06-28 00:56:51.857981

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5aab647f5151'
down_revision = '5f07701d2bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shows', 'venue_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('Shows', 'artist_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_foreign_key(None, 'Shows', 'Venues', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'Shows', 'Shows', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.alter_column('Shows', 'artist_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('Shows', 'venue_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
