"""empty message

Revision ID: 5f07701d2bb2
Revises: 37ec846e06cc
Create Date: 2021-06-28 00:39:05.310653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f07701d2bb2'
down_revision = '37ec846e06cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('Venues', 'seeking_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venues', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Venues', 'seeking_talent')
    # ### end Alembic commands ###
