"""empty message

Revision ID: 8d17d1e9661b
Revises: 5aab647f5151
Create Date: 2021-06-28 04:58:46.813429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d17d1e9661b'
down_revision = '5aab647f5151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Shows_artist_id_fkey', 'Shows', type_='foreignkey')
    op.create_foreign_key(None, 'Shows', 'Artists', ['artist_id'], ['id'])
    op.drop_column('Shows', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Shows_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.create_foreign_key('Shows_artist_id_fkey', 'Shows', 'Shows', ['artist_id'], ['id'])
    # ### end Alembic commands ###
