"""empty message

Revision ID: e3eb5752e834
Revises: 71a86beb5712
Create Date: 2021-07-09 20:31:47.790874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3eb5752e834'
down_revision = '71a86beb5712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venues', sa.Column('perro', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venues', 'perro')
    # ### end Alembic commands ###
